version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    #networks:
    #  - jeera_network
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    image: backend
    container_name: backend
    build:
      context: backend
      dockerfile: backend/Dockerfile
    depends_on:
      - db

networks:
  jeera_network:
    external: true